In [22]:
import pandas as pd
import numpy as np

In [2]:
import os, sys
sys.path.append(os.path.join(os.path.expanduser('~'), 'Documents/Insert-Generic-Name-Here/'))
# sys.path

from lonelyboy.geospatial import plots as gsplt
from lonelyboy.geospatial import preprocessing as gspp
from lonelyboy.timeseries import lbtimeseries as tspp

In [3]:
fisheries = pd.read_csv('data/csv/fisheries_dynamic_real_points_v3.csv')

In [4]:
%%time
fisheries = gspp.gdf_from_df(fisheries)

CPU times: user 1min 8s, sys: 400 ms, total: 1min 8s
Wall time: 1min 7s


In [5]:
fisheries.sort_values('ts', inplace=True)

In [6]:
fisheries.reset_index(drop=True, inplace=True)

In [7]:
fisheries

mmsi  course       lon        lat          ts   velocity  \
0        228131600   263.7 -4.644325  48.092247  1443650404  11.590369   
1        228037600    90.2 -4.448573  48.157547  1443650409  12.111672   
2        227443000   171.5 -4.782632  48.005634  1443650411  12.628942   
3        228131600   265.2 -4.644965  48.092180  1443650416  12.593468   
4        228037600    87.6 -4.448013  48.157574  1443650419  13.535968   
5        227443000   172.6 -4.782532  48.005116  1443650420  10.235945   
6        228131600   260.9 -4.645487  48.092130  1443650425  14.013235   
7        228037600    87.2 -4.447327  48.157630  1443650430  15.065887   
8        227443000   173.7 -4.782448  48.004600  1443650431  12.154994   
9        228131600   269.4 -4.646070  48.092106  1443650434  12.523681   
10       228931000    85.1 -4.483470  48.115280  1443650438  12.966388   
11       228037600    86.8 -4.446700  48.157658  1443650439  12.318036   
12       228131600   266.2 -4.646707  48.092075  1443650445  12.669158   
13       228037600    87.2 -4.446073  48.157680  1443650450  13.444377   
14       227443000   171.7 -4.782232  48.003550  1443650450  10.626990   
15       228131600   264.9 -4.647292  48.092040  1443650455  12.604107   
16       228931000    83.0 -4.482276  48.115402  1443650458  13.032950   
17       228037600    88.2 -4.445452  48.157696  1443650460  13.481863   
18       227443000   171.1 -4.782132  48.003067  1443650460  12.686616   
19       228131600   266.1 -4.647815  48.092000  1443650464  11.801152   
20       227443000   172.5 -4.782015  48.002550  1443650469  11.255820   
21       228037600    85.4 -4.444829  48.157722  1443650470  13.533994   
22       228131600   263.6 -4.648468  48.091953  1443650476  12.677213   
23       228037600    82.5 -4.444267  48.157770  1443650479  13.503431   
24       227443000   173.8 -4.781915  48.001984  1443650480   9.985854   
25       228131600   262.5 -4.648995  48.091915  1443650485  12.642672   
26       228037600    85.3 -4.443582  48.157820  1443650490  13.616012   
27       227443000   172.0 -4.781815  48.001484  1443650491  11.461407   
28       228131600   261.3 -4.649573  48.091827  1443650495  14.020235   
29       228037600    86.8 -4.443015  48.157840  1443650499  13.475909   
...            ...     ...       ...        ...         ...        ...   
2525678  227635680   194.2 -4.768385  48.048195  1459461446  13.971725   
2525679  228037600   156.1 -4.321293  48.163567  1459461448  11.137113   
2525680  227635680   209.9 -4.768673  48.047688  1459461455  10.372287   
2525681  228037600   160.1 -4.321078  48.163155  1459461457  10.094237   
2525682  227635680   179.5 -4.768786  48.047220  1459461465  11.324070   
2525683  228037600   159.5 -4.320830  48.162704  1459461468   9.036206   
2525684  227635680   182.7 -4.768805  48.046642  1459461476  11.508738   
2525685  228037600   161.4 -4.320633  48.162334  1459461478   9.992974   
2525686  228160000   238.5 -4.530364  48.093410  1459461483   9.028638   
2525687  227635680   182.6 -4.768887  48.046060  1459461487  13.777253   
2525688  228160000   206.4 -4.530450  48.093174  1459461489   8.404299   
2525689  228037600   162.0 -4.320402  48.161880  1459461489  10.413212   
2525690  227635680   184.2 -4.768995  48.045560  1459461495  10.574523   
2525691  228160000   188.0 -4.530447  48.092940  1459461495   9.212280   
2525692  228160000   190.2 -4.530477  48.092860  1459461497  10.140536   
2525693  228160000   225.3 -4.530770  48.092712  1459461504  11.667733   
2525694  227635680   182.3 -4.769000  48.045020  1459461506  12.723506   
2525695  228160000   242.2 -4.530932  48.092700  1459461507   8.675664   
2525696  227635680   169.3 -4.768917  48.044495  1459461515  10.379679   
2525697  228160000   289.4 -4.531233  48.092810  1459461515   4.594333   
2525698  228160000   301.5 -4.531261  48.092842  1459461517  11.264047   
2525699  228160000   316.9 -4.531490  48.093056  1459461523  11.117227   
2525700  227635680

## Calculating the Basic Features of the ML Dataset

In [8]:
fisheries_ml_env = fisheries.groupby(['mmsi', 'trip_id'], group_keys=False).apply(lambda x: x[['ts', 'lon', 'lat', 'velocity']].values).reset_index()

In [36]:
fisheries.loc[(fisheries.mmsi == 219017843) & (fisheries.trip_id == 0)]

mmsi  course       lon        lat          ts  velocity  trip_id  \
602983  219017843    96.0 -4.375318  48.128647  1448336331  5.473559        0   
602984  219017843    97.1 -4.375168  48.128624  1448336337  0.094769        0   

                   datetime                          geom  
602983  2015-11-24 03:38:51  POINT (-4.3753185 48.128647)  
602984  2015-11-24 03:38:57  POINT (-4.3751683 48.128624)

In [37]:
np.set_printoptions(suppress=True, formatter={'float_kind':'{:f}'.format})

print(fisheries_ml_env.values)

[[219017843 0
  array([[1448336331.000000, -4.375318, 48.128647, 5.473559],
       [1448336337.000000, -4.375168, 48.128624, 0.094769]])]
 [219017843 1
  array([[1457928735.000000, -4.833392, 48.205166, 17.184613],
       [1457928815.000000, -4.827582, 48.202568, 16.307824],
       [1457928856.000000, -4.824772, 48.201270, 17.425203],
       [1457929115.000000, -4.805262, 48.193806, 17.612581],
       [1457929175.000000, -4.800658, 48.192154, 15.831242],
       [1457929186.000000, -4.799900, 48.191880, 19.093977],
       [1457929195.000000, -4.799163, 48.191580, 16.723447],
       [1457929217.000000, -4.797567, 48.190987, 17.748043],
       [1457929357.000000, -4.786535, 48.187744, 19.301054],
       [1457929385.000000, -4.784133, 48.187046, 17.765690],
       [1457929446.000000, -4.779326, 48.185616, 19.500884],
       [1457929456.000000, -4.778463, 48.185352, 15.767594],
       [1457929466.000000, -4.777767, 48.185135, 20.457170],
       [1457929476.000000, -4.776855, 48.184880, 15.9

In [39]:
np.save('data/npy/fisheries_dynamic_V3_ml_extra_features_V2.npy', fisheries_ml_env[0].values) 

#### Save Vessel Trip Metadata

In [72]:
fisheries_ml_env_meta = fisheries_ml_env.iloc[:,:2]
fisheries_ml_env_meta['id'] = fisheries_ml_env_meta.index
fisheries_ml_env_meta.to_csv('data/npy/fisheries_dynamic_V3_ml_metadata.csv', header=True, index=False)

In [73]:
fisheries_ml_env_meta.head()

mmsi  trip_id  id
0  219017843        0   0
1  219017843        1   1
2  219017843        2   2
3  224038000        0   3
4  224038000        1   4

#### Acknowledging the Correctness of the Result
* #### Comparing the Trajectory Length from the Original Data with the ML Data using their Respective MetaData

In [41]:
%%time
test = np.load('data/npy/fisheries_dynamic_V3_ml_extra_features_V2.npy')
test_meta = pd.read_csv('data/npy/fisheries_dynamic_V3_ml_metadata.csv')

for traj in test_meta.itertuples():
    traj_tmp = len(fisheries.loc[(fisheries.mmsi == traj.mmsi) & (fisheries.trip_id == traj.trip_id)])
    traj_tmp_ml = test[traj.Index].shape[0]
    
    if not traj_tmp == traj_tmp_ml:
        print ('SHIT')

CPU times: user 2min 48s, sys: 15.8 ms, total: 2min 48s
Wall time: 42.5 s


In [20]:
test

array([array([[-4.3753185 , 48.128647  ,  5.47355923],
       [-4.3751683 , 48.128624  ,  0.0947689 ]]),
       array([[-4.8333917 , 48.205166  , 17.18461288],
       [-4.827582  , 48.202568  , 16.30782413],
       [-4.824772  , 48.20127   , 17.42520349],
       [-4.8052616 , 48.193806  , 17.6125806 ],
       [-4.800658  , 48.192154  , 15.83124172],
       [-4.7999    , 48.19188   , 19.09397672],
       [-4.7991633 , 48.19158   , 16.72344703],
       [-4.797567  , 48.190987  , 17.74804262],
       [-4.786535  , 48.187744  , 19.30105444],
       [-4.7841334 , 48.187046  , 17.76569047],
       [-4.7793264 , 48.185616  , 19.50088379],
       [-4.7784634 , 48.185352  , 15.76759353],
       [-4.7777667 , 48.185135  , 20.4571702 ],
       [-4.776855  , 48.18488   , 15.96958048],
       [-4.7761536 , 48.184647  , 18.72712986],
       [-4.77532   , 48.18441   , 17.46984855],
       [-4.774628  , 48.184185  , 18.36049854],
       [-4.7737317 , 48.18392   , 20.09422079],
       [-4.7729216 , 48.

## Calculating the Extra Features of the ML Dataset
* ## Acceleration and Bearing

In [ ]:
%%time
fisheries_extra_features_acceleration = fisheries.groupby(['mmsi', 'trip_id'], group_keys=False).apply(lambda x: gspp.calculate_acceleration(x))

In [ ]:
fisheries_extra_features_acceleration

In [ ]:
%%time
fisheries_extra_features_bearing = fisheries_extra_features_acceleration.groupby(['mmsi', 'trip_id'], group_keys=False).apply(lambda x: gspp.calculate_bearing(x))

In [ ]:
fisheries_extra_features_bearing

In [ ]:
fisheries_ml_env_v2_extra_features = fisheries_extra_features_bearing.groupby(['mmsi', 'trip_id'], group_keys=False).apply(lambda x: x[['lon', 'lat', 'velocity', 'acceleration', 'bearing']].values).reset_index()

In [ ]:
np.save('data/npy/fisheries_dynamic_V3_ml_extra_features_acceleration_bearing.npy', fisheries_ml_env_v2_extra_features[0].values) 

## Organizing .npy Files with their Metadata

In [ ]:
fisheries_extra_features_bearing[0].apply(len)

In [ ]:
fisheries_ml_env_v2_extra_features[0].apply(len)

In [ ]:
fisheries_ml_env[0].apply(len)